config/routes.rb
Wherzmamoney::Application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    post 'login'   => 'users#login',   :as => 'login'
    get  'logout'  => 'users#logout',  :as => 'logout'
    get  'welcome' => 'users#welcome', :as => 'welcome'

    get 'incomes/csv'  => 'incomes#csv'
    get 'incomes/edit' => 'incomes#edit'

    get 'outgoes/csv'  => 'outgoes#csv'
    get 'outgoes/edit' => 'outgoes#edit'

    get 'transactions/by_year'         => 'transactions#year_extract'
    get 'transactions/by_year/:year'   => 'transactions#year_extract'
    get 'transactions/modals/by-month' => 'transactions#months_modal'
    get 'transactions/modals/by-year'  => 'transactions#years_modal'
    get 'transactions/search'          => 'transactions#search'

    resources :import_export, :only => [:create, :index, :show]
    resources :incomes
    resources :ng_views, :only => :show
    resources :outgoes
    resources :users
    resources :transactions, :only => :index

    root :to => 'ng_views#show'
  end

  match '*path', via: [:get, :post], to: redirect("/#{I18n.default_locale}/%{path}")
  match '', via: [:get, :post], to: redirect("/#{I18n.default_locale}/")

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :email, :name, :password, :password_confirmation

  attr_accessor :password
  before_save :encrypt_password

  has_many :categories
  has_many :incomes
  has_many :outgoes
  has_many :sources
  has_many :tags
  has_many :transactions

  validates :password, :presence => true, :confirmation => true
  validates :email, :presence => true, :uniqueness => true

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_digest == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_digest = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/users_controller.rb
# encoding: UTF-8
class UsersController < ApplicationController
  skip_before_filter :require_authentication, :only => [:create, :login, :welcome]

  def update
    # Código abaixo não funciona
    if User.authenticate(current_user.email, params[:current_password])
      if @user = current_user.update_attributes(params[:user])
        #se salvar
      else
        #se não salvar
      end
    else
      #se "senha atual" nao corresponder
      #retornar erros (em json?)
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Cadastrado"
    else
      render :text => "welcome"
    end
  end

  def login
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url
    else
      # TODO
      # Redirecionamento para URL passada em parâmetros não está runcionando
      redirect_to params[:redirect_url] || welcome_path
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to welcome_path
  end

  def welcome
    @new_user = User.new
    @user = current_user

    render :layout => nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_login_form.html.haml
= form_tag login_path, { :id => "login_form", :'ng-show' => "isLoginEmailFormVisible" } do
  %input{ :type => "hidden", :name => "redirect_url", :value => "{{reditectUrl}}" }

  .row
    .large-12.columns
      %label= t "users.login_with_email_address"

  .row
    .large-12.columns
      = email_field_tag :email, "", { :placeholder => t("users.email_address"), :required => "" }

  .row
    .large-12.columns
      = password_field_tag :password, "", { :placeholder => t("users.password"), :required => "" }

  .row
    .large-12.columns
      = check_box_tag "keep_conection", true, false
      = label_tag "keep_conection", "Mantenha-me conectado"

  .row
    .large-12.columns
      = submit_tag t(".login"), :class => 'button radius small-full'

  .row
    .large-12.columns
      %a{ :href => '#/recover-password' } Forgot your password?

app/views/users/_signup_form.html.haml
= form_for(@new_user, html: { id: 'signup_form', :'ng-show' => "isSignUpEmailFormVisible" }) do |f|
  .row
    .large-12.columns
      %label=t "users.sign_up_with_email_address"

  .row
    .large-12.columns
      = f.text_field :name, { :placeholder => t("users.full_name") }

  .row
    .large-12.columns
      = f.email_field :email, { :placeholder => t("users.email_address"), :required => "" }

  .row
    .large-12.columns
      = f.password_field :password, { :placeholder => t("users.password"), :'ng-model' => 'password', :required => ""  }

  .row{ :'ng-show' => 'password.length > 0' }
    .large-12.columns
      = f.password_field :password_confirmation, { :placeholder => t("users.password_confirmation"), :required => "" }

  .row
    .large-12.columns
      = f.submit t(".sign_me_up"), class: 'button radius small-full'

app/views/users/welcome.html.haml
= render :partial => "shared/topbar", :locals => { :'menus_enabled' => false }

%section.main-section.welcome
  %dl.tabs( data-tabs )
    %dd{ :'ng-class' => "{ active: location == 'signup' }" }
      %a{ :href => "#signup" }=t ".sign_up"
    %dd{ :'ng-class' => "{ active: location == 'login' }" }
      %a{ :href => "#login" }=t ".login"
    %dd{ :'ng-class' => "{ active: location == 'watzit' }" }
      %a{ :href => "#watzit" }=t ".watzit.title"

  .tabs-content
    #signup.content{ :'ng-class' => "{ active: location == 'signup' }" }

      .row.social-buttons.unavailable
        .large-12.columns
          %a.fb.button.radius.full
            %span.icon.icomoon.left &#xe765;
            =t ".sign_up_with_facebook"

          %a.google.button.radius.full
            %span.icon.icomoon.left &#xe760;
            =t ".sign_up_with_google_plus"

      = render :partial => "users/signup_form"

      .row.footer-links
        .large-12.columns
          %a{ :'ng-click' => "showSignUpEmailForm()", :'ng-show' => "!isSignUpEmailFormVisible" }
            =t "users.sign_up_with_email_address"

          %a{ :href => '#/login' }=t ".footer_links.login"
          %a{ :href => '#/watzit' }=t ".footer_links.watzit"

    #login.content{ :'ng-class' => "{ active: location == 'login' }" }

      .row.social-buttons.unavailable
        .large-12.columns
          %a.fb.button.radius.full
            %span.icon.icomoon.left &#xe765;
            =t ".login_with_facebook"

          %a.google.button.radius.full
            %span.icon.icomoon.left &#xe760;
            =t ".login_with_google_plus"

      = render :partial => "users/login_form"

      .row.footer-links
        .large-12.columns
          %a{ :'ng-click' => "showLoginEmailForm()", :'ng-show' => "!isLoginEmailFormVisible" }
            =t "users.login_with_email_address"

          %a{ :href => '#/signup' }=t ".footer_links.sign_up"
          %a{ :href => '#/watzit' }=t ".footer_links.watzit"

    #watzit.content{ :'ng-class' => "{ active: location == 'watzit' }" }
      .row
        .large-12.columns
          %p=t ".watzit.text.tired"
          %p=t ".watzit.text.problem_end"
          %p
            =t ".watzit.text.control"
            %strong=t "app_name"
          %p
            %a{ :href => '#/signup' }=t ".create_account_now"
            =t ".watzit.text.it_is_free"
          %p=t ".watzit.text.totally_excelent"

          %a.button.radius.small-full{ :href => '#/signup' }=t ".create_an_account"